CC := g++
JOB = job
PREFIX := obj/
SRC := main.cpp Vector.cpp Vector.h Person.cpp Person.h Dialog.cpp Dialog.h Abiturient.cpp Abiturient.h
OBJ := $(patsubst %.cpp, $(PREFIX)%.o, $(SRC))

$(JOB): $(OBJ)
	$(CC) -o $@ $^

$(PREFIX)%.o: %.cpp
	$(CC) -c -o $@ $^

debug: $(JOB)
	gdb -x gdb.config $(JOB)

cod:  $(SRC)
	mintty emacs $(SRC)

clean:
	rm -rf *.exe $(PREFIX)*.o
