 @startuml
note left of main #while: Комментарий.
note top of Rightangled : Комментарий.
note top of Object : Комментарий.
note top of Vector : Комментарий.
main --> Rightangled
main --> Pain
main ..> Object
main ..> Vector
Object ..> Vector
Rightangled --> Pain
class main<<(m,#FF7700)>>{
    Vector v
    Pair a
    Rightangled b
    Object* p = &a
} 
abstract class Object{
    + virtual void Show() = 0
}
class Rightangled{
    .. protected varible ..
    # int hypatenuse
    .. public metod ..
    + void set_hypatenuse(int)
    + int get_hypatenuse() 
    + int Hypatenuse()
    .. friend metod ..
    + Rightangled& operator = (const Rightangled&)
    + friend istream& operator >> (istream& in,  Rightangled& rightangled)
    + friend ostream& operator << (ostream& out, const Rightangled& rightangled)
}
class Pain{
    .. public varible ..
    + int  perimeter
    .. protected varible ..
    # int first
    # int second
    .. public metod ..
    + int  get_first()
    + int  get_second() 
    + int  set_first()
    + int  set_second()
    + Pair& operator= (const Pair&)
    .. friend metod ..
    + friend istream& operator >> (istream &in, Pair& pair)
    + friend ostream& operator << (ostream &out, const Pair& pair)
}
class Vector{
    .. privat varible ..
    - Object** beg
    - int size
    + void Add(Object*)
    .. friend metod ..
    + friend ostream& operator<< (ostream &out, const Vector&)
}
 @enduml

